// src/lib/components/ExtensionCategory.svelte
<script lang="ts">
    import ExtensionCard from './ExtensionCard.svelte';
    import type { ExtensionRepo } from '$lib/types';

    interface Props {
        category: string;
        repos: ExtensionRepo[];
        selectedDomain: string;
    }

    let { category, repos, selectedDomain }: Props = $props();

    let protocol = $derived(category.toLowerCase() === 'mihon' ? 'tachiyomi' : 'aniyomi');
    let title = $derived(category.charAt(0).toUpperCase() + category.slice(1));
</script>

<div class={category}>
    <h2>{title} Extensions</h2>
    <div class="grid">
        {#each repos as repo}
            <ExtensionCard {repo} {protocol} {selectedDomain} />
        {/each}
    </div>
</div>

// src/components/ExtensionCategory.tsx
import { FunctionComponent } from 'preact';
import { ExtensionCard } from './ExtensionCard';

interface ExtensionCategoryProps {
    category: string;
    repos: Array<{
        source: string;
        name: string;
        path: string;
        commit?: string;
    }>;
    selectedDomain: string;
}

export const ExtensionCategory: FunctionComponent<ExtensionCategoryProps> = ({ category, repos, selectedDomain }) => {
    const protocol = category.toLowerCase() === 'mihon' ? 'tachiyomi' : 'aniyomi';

    return (
        <div class={category}>
            <h2>{category.charAt(0).toUpperCase() + category.slice(1)} Extensions</h2>
            <div class="grid">
                {repos.map((repo) => (
                    <ExtensionCard repo={repo} protocol={protocol} selectedDomain={selectedDomain} />
                ))}
            </div>
        </div>
    );
};
