// src/components/Footer.tsx
import { FunctionComponent } from 'preact';

interface FooterProps {
    source: string;
    commitLink: string;
    latestCommitHash: string;
}

export const Footer: FunctionComponent<FooterProps> = ({ source, commitLink, latestCommitHash }) => {
    return (
        <footer>
            Source Code: <a href={source} target="_blank">{source}</a>
            <div>
                Commit: <a href={commitLink} target="_blank">{latestCommitHash}</a>
            </div>
        </footer>
    );
};

// src/lib/components/Footer.svelte
<script lang="ts">
    interface Props {
        source: string;
        commitLink: string;
        latestCommitHash: string;
    }

    let { source, commitLink, latestCommitHash }: Props = $props();
</script>

<footer>
    Source Code: <a href={source} target="_blank">{source}</a>
    <div>
        Commit: <a href={commitLink} target="_blank">{latestCommitHash}</a>
    </div>
</footer>
